### ISSUE TITLE
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments require...

### ISSUE THREAD

**Issue by mik9** [ionnetwork/atom-swd-debugger#3]
1. Cmd+D to show debugger
2. Cmd+D to hide debugger
3. Issue occurs.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [swd-debugger](https://github.com/ionnetwork/atom-swd-debugger) package 0.1.1

### Stack Trace

Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

```
At /Users/mik/.atom/packages/swd-debugger/lib/debugger-view.coffee:378

TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at TypeError (native)
    at DebuggerView.module.exports.DebuggerView.destroy (/packages/swd-debugger/lib/debugger-view.coffee:378:22)
    at Object.toggle (/packages/swd-debugger/lib/debugger.coffee:38:21)
    at /packages/swd-debugger/lib/debugger.coffee:21:83)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at HTMLDivElement.coreConfirm (/app.asar/node_modules/atom-select-list/src/select-list-view.js:67:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:23.9.0 debugger:toggle (input.hidden-input)
     -1:08.8.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:08.6.0 core:paste (input.hidden-input)
     -1:02.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:02.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:02.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:02.1.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:52.8.0 core:paste (input.hidden-input)
  2x -0:51.3.0 core:backspace (input.hidden-input)
     -0:46.6.0 core:save (input.hidden-input)
     -0:44.2.0 command-palette:toggle (input.hidden-input)
     -0:42.9.0 core:confirm (input.hidden-input)
     -0:42.9.0 debugger:toggle (input.hidden-input)
     -0:14.3.0 command-palette:toggle (input.hidden-input)
     -0:13.3.0 core:confirm (input.hidden-input)
     -0:13.3.0 debugger:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.10.1 
build 0.67.0 
build-make 0.13.0 
busy 0.7.0 
file-icons 2.1.2 
swd-debugger 0.1.1 
terminal-plus 0.14.5 
```

**Comment by cometu** [comment]
I have the same issue
